# Support this open-source project by using the funding links below.
# Created by Waren Gonzaga, developed and maintained by Wareneutron Developers.

custom: ['https://wareneutron/donate']

# Your donation and support means a lot to us to continue the development of our open source projects just like this.
