# Support this open-source project and us by using the official donation link below.
# Created by Waren Gonzaga, developed and maintained by Wareneutron Developers.

custom: ['https://wareneutron.com/donate']

# Your donation means a lot to us to continue the development of our open source projects just like this.
